version: "3.1"
nlu:
- intent: bot_challenge
  examples: |
    - are you a bot?
    - am I talking to a human?
    - am I talking to a bot?
- intent: emotion_review
  examples: |
    - good movie
    - boring movie
    - terrible experience
- intent: request_names
  examples: |
    - give name
    - do you know my name?
    - i want to give you my name
- intent: send_email
  examples: |
    - email
    - Send an email
    - I want to to send email
- intent: weather
  examples: |
    - Weather
    - How is the weather today?
    - What is the weather?
- intent: sad_reasons
  examples: |
    - I am so alone
    - I am just sad, I am not sure about the reason.
    - I feel so lonely.
    - I have nobody to talk to.
- intent: out_of_scope
  examples: |
    - Are you alive?
    - Calculate 10+1?
    - tell me a joke
    - What is your favourite music?
- intent: deny
  examples: |
    - n
    - not really
    - don't like that
    - never
    - nope
    - no
    - no way
- intent: affirm
  examples: |
    - y
    - yeah
    - of course
    - yes
    - Yes
    - indeed
    - that sounds good
- intent: city
  examples: |
    - Amsterdam
    - Newyork
    - Tokyo
    - Belgium
    - Sydney
    - Delhi
    - Belfast
- intent: goodbye
  examples: |
    - goodbye
    - good by
    - have a nice day
    - cee you later
    - bye bye
    - see you around
    - bye
    - cu
- intent: greet
  examples: |
    - good evening
    - good morning
    - let's go
    - goodmorning
    - hello
    - hey there
    - good afternoon
    - hello there
    - hey
    - goodevening
    - hey dude
- intent: greet_with_name
  examples: |
    - goodmorning chatbot
    - good morning bot
    - goodevening bot
    - let's go bot
    - good afternoon chatbot
    - hey bot
    - good evening bot
    - hey dude bot
    - hey there bot
    - hello rasa
- intent: query_knowledge_base
  examples: |
    - list some [diseases]{"entity": "object_type", "value": "disease"}
    - How to [diagnose]{"entity": "attribute", "value": "suggest_diagnosis"} [Diabetes](disease)
    - what [diseases]{"entity": "object_type", "value": "disease"} do you know about?
    - What are the [symptoms](attribute) of [Diabetes](disease)
    - [Whom]{"entity": "attribute", "value": "doctor_type"} to consult for [Diabetes](disease)
    - What are the [risks]{"entity": "attribute", "value": "leads_to"} of [Diabetes] {"entity":"disease"}
    - what are the [precautions]{"entity": "attribute", "value": "precaution"} for [Diabetes](disease)
    - what is the [cause](attribute) of [Diabetes](disease)?
    - do you know the [cure](attribute) of [Diabetes](disease)
    - does [Diabetes](disease) have [cause](attribute)?
    - what [cures]{"entity": "attribute", "value": "cure"} [Diabetes](disease)
- intent: mood
  examples: |
    - not good
    - so so perfect
    - fine
    - so saad
    - super sad
    - so good
    - great
    - perfect
    - so sad
    - I am sad
    - I am great
    - feeling like a king
    - I am feeling very good
    - extremly sad
    - nervous
    - unhappy
    - very sad
    - I am going to save the world
    - well
    - sad
    - I am disappointed
    - super stoked
    - extremely good
    - I am amazing
    - not very good
    - I'm so sad
    - so perfect
- synonym: disease
  examples: |
    - diseases
    - illness
    - sickness
- synonym: cure
  examples: |
    - cures
    - heal
    - restore
    - revive
    - make better
- synonym: precaution
  examples: |
    - precautions
    - protection
    - safeguard
    - caution
    - prevent
- synonym: doctor_type
  examples: |
    - Whom
- synonym: suggest_diagnosis
  examples: |
    - diagnose
- synonym: leads_to
  examples: |
    - risks
    - give rise to
    - bring about
    - complications
    - leads to
- synonym: Definition
  examples: |
    - Define
    - Explain
    - Tell me about
    - What
    - definition
- synonym: cause
  examples: |
    - reason
    - why
    - origin
- synonym: doctor type
  examples: |
    - type of doctor
    - kind of doctor
    - which doctor
    - What doctor
    - doctor
    - doctors
- synonym: symptoms
  examples: |
    - ailment
    - disorder
    - malady
    - symptom
- synonym: Diagnose
  examples: |
    - identify
    - find out
    - recognize
- lookup: disease
  examples: |
    - Diabetes
    - Depression
    - Schizophrenia
    - Anxiety
    - Acne
    - PCOD
    - Hormonal imbalance
    - Common cold
    - Bipolar disorder
    - Thyroid
- lookup: doctor_type
  examples: |
    - General Practitioner and Endocrinologist
    - Psychiatrist
    - A psychiatrist experienced in treating schizophrenia usually guides treatment
    - Dermatologists
    - Gynecologist, Endocrinologist or Reproductive Endocrinologist
    - Endocrinologist
    - Family practice physicians, pediatricians, and internists
    - Thyroidologists
